### ISSUE TITLE
Use of Nil in string context and some other errors.

### ISSUE THREAD

**Issue by zhuomingliang** [tony-o/perl6-zef#1]
➜  perl6-zef git:(master) PATH=$PATH:../MoarVM/install/bin ./bin/zef.pl6 install CSV::Parser
Use of Nil in string context  in sub gethome at /home/cloud/OpenSource/perl6-zef/lib/Zef/Utils.pm:55
Use of Nil in string context  in sub gethome at /home/cloud/OpenSource/perl6-zef/lib/Zef/Utils.pm:55
Use of Nil in string context  in sub gethome at /home/cloud/OpenSource/perl6-zef/lib/Zef/Utils.pm:55
Use of Nil in string context  in sub gethome at /home/cloud/OpenSource/perl6-zef/lib/Zef/Utils.pm:55
Use of Nil in string context  in sub gethome at /home/cloud/OpenSource/perl6-zef/lib/Zef/Utils.pm:55
Use of Nil in string context  in sub gethome at /home/cloud/OpenSource/perl6-zef/lib/Zef/Utils.pm:55
test: True
[INFO ]: Downloading META data for CSV::Parser
True
Use of Nil in string context  in block  at /home/cloud/OpenSource/perl6-zef/lib/Zef/EZRest.pm6:34
# Saw 6 occurrences of deprecated code.

$*OS seen at:
  /home/cloud/OpenSource/perl6-zef/lib/Zef/Test.pm, line 26
Deprecated since v2014.9, will be removed with release v2015.9!
## Please use $*DISTRO.name instead.

Semicolon form of 'class' without 'unit' seen at:
  /home/cloud/OpenSource/perl6-zef/lib/Zef/Test.pm, line 1
Deprecated since v2015.4, will be removed with release v2015.9!
  /home/cloud/OpenSource/perl6-zef/lib/Zef/Auth.pm, line 1
Deprecated since v2015.4, will be removed with release v2015.9!
  /home/cloud/OpenSource/perl6-zef/lib/JSON/Tiny/Actions.pm, line 1
Deprecated since v2015.4, will be removed with release v2015.9!
  /home/cloud/OpenSource/perl6-zef/lib/Zef/Search.pm, line 1
Deprecated since v2015.4, will be removed with release v2015.9!
  /home/cloud/OpenSource/perl6-zef/lib/Zef/Install.pm, line 1
Deprecated since v2015.4, will be removed with release v2015.9!
  /home/cloud/OpenSource/perl6-zef/lib/Zef/Push.pm, line 1
Deprecated since v2015.4, will be removed with release v2015.9!
## Please use 'unit class' instead.

Semicolon form of 'grammar' without 'unit' seen at:
  /home/cloud/OpenSource/perl6-zef/lib/JSON/Tiny/Grammar.pm, line 2
Deprecated since v2015.4, will be removed with release v2015.9!
## Please use 'unit grammar' instead.

Semicolon form of 'module' without 'unit' seen at:
  /home/cloud/OpenSource/perl6-zef/lib/Zef/Utils.pm, line 1
Deprecated since v2015.4, will be removed with release v2015.9!
  /home/cloud/OpenSource/perl6-zef/lib/JSON/Tiny.pm, line 16
Deprecated since v2015.4, will be removed with release v2015.9!
## Please use 'unit module' instead.

Method send (from IO::Socket) seen at:
  /home/cloud/OpenSource/perl6-zef/lib/Zef/EZRest.pm6, line 80
Deprecated since v2015.7, will be removed with release v2015.9!
## Please use print instead.

Method path (from Str) seen at:
  ./bin/zef.pl6, lines 7,8
Deprecated since v2014.11, will be removed with release v2015.9!
## Please use IO instead.

Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!

Please note that _ALL_ deprecated features will be removed at the RC-0 release
(expected September 2015).

**Comment by tony-o** [comment]
Sorry for the confusion.  I updated the README to reflect that this repo is no longer used in favor of https://github.com/ugexe/zef
